name: Continuous Integration

on: [pull_request]

jobs:

  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Installing project dependencies
      run: |
        npm install
    - name: Lint
      run: |
        npm run lint